spring:
  datasource:
    url: jdbc:h2:mem:foodmap;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

cloud:
  aws:
    s3:
      bucket: _
    credentials:
      access-key: _
      secret-key: _
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
